---
- name: install mysql-server
  apt:
    name: mysql-server
    state: present
    update_cache: true

- name: install python3-pymysql
  apt:
    name: python3-pymysql
    state: present

- name: Create a new database with name 'wordpress'
  community.mysql.mysql_db:
    name: wordpress
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Create database user with name 'wordpress' with all priviledge
  community.mysql.mysql_user:
    name: wordpress
    password: "{{ db_password }}"
    priv: '*.*:ALL'
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock